name: Check MOSAiC

on:
  push:
    branches:
      - main
      - develop

jobs:
  correspondence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: python -m pip install -r ./MOSAiC/dev/check/requirements.txt
      - run: python ./MOSAiC/dev/check/check.py
  schacl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: python -m pip install pyshacl
      - run: pyshacl -s ./MOSAiC/dev/shapes.shacl -df xml -sf turtle ./MOSAiC/MOSAiC.owl
