name: Check MOSAiC

on:
  push:
    branches:
      - main
      - feature-105-mosaic-check

jobs:
  SHACL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: python -m pip install -r ./MOSAiC/dev/check/requirements.txt
      - run: python ./MOSAiC/dev/check/check.py
